### ISSUE TITLE
最新的也会一直签名验证失败

### ISSUE THREAD

**Issue by forchannot** [HarbourJ/Temp#5]

**Comment by zhengxujin** [comment]
我也是

**Comment by xiejiangchu** [comment]
看抽奖视频161-100失败：签名验证失败

**Comment by pk25boy** [comment]
TypeError: Cannot read properties of null (reading '1')
    at new _0x9d8dda (/ql/scripts/raw_main_ksjsb_0512.js:240:40)
    at _0x2dc359 (/ql/scripts/raw_main_ksjsb_0512.js:1081:30)
    at /ql/scripts/raw_main_ksjsb_0512.js:935:17
    at Object.<anonymous> (/ql/scripts/raw_main_ksjsb_0512.js:1055:3)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
  请问怎么弄？谢谢了

**Comment by kongbg** [comment]
> TypeError: Cannot read properties of null (reading '1') at new _0x9d8dda (/ql/scripts/raw_main_ksjsb_0512.js:240:40) at _0x2dc359 (/ql/scripts/raw_main_ksjsb_0512.js:1081:30) at /ql/scripts/raw_main_ksjsb_0512.js:935:17 at Object. (/ql/scripts/raw_main_ksjsb_0512.js:1055:3) at Module._compile (node:internal/modules/cjs/loader:1097:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10) at Module.load (node:internal/modules/cjs/loader:975:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) at node:internal/main/run_main_module:17:47 请问怎么弄？谢谢了

十有八九是ck格式不对导致的

**Comment by pk25boy** [comment]
能指教下怎么设置吗？平常在环境变量和配置文件中都设置了能用

**Comment by mingzi199002** [comment]
看抽奖视频161-213失败：签名验证失败

**Comment by tzxiaozhen88** [comment]
黄花菜了。凉凉的了。

**Comment by weis1655** [comment]
## 开始执行... 2022-05-13 16:52:04


=========== 胖大海 ===========

账号[胖大海]任务完成情况：
【最高5000金币悬赏】 0/10，未完成，每次运行完成1次任务

【最高12000金币看直播】 0/10，未完成，每次运行完成1次任务
【逛街领1000金币】 0/10，未完成，每次运行完成1次任务
【抽奖领最高5000金币】 0/60，未完成，每次运行完成5次任务


账号[胖大海]看抽奖视频161-100失败：签名验证失败

账号[胖大海]看抽奖视频11-100失败：签名验证失败

账号[胖大海]看抽奖视频161-100失败：签名验证失败

账号[胖大海]看抽奖视频11-100失败：签名验证失败

账号[胖大海]看抽奖视频161-100失败：签名验证失败

账号[胖大海]看抽奖视频11-100失败：签名验证失败

账号[胖大海]看抽奖视频161-100失败：签名验证失败

账号[胖大海]看抽奖视频11-100失败：签名验证失败

账号[胖大海]看抽奖视频161-100失败：签名验证失败

账号[胖大海]看抽奖视频11-100失败：签名验证失败

**Comment by HarbourJ** [comment]
现在都不能用了。

**Comment by fjqzaxljm** [comment]
签名验证失败
